spring:
    datasource:
      url: jdbc:mysql://localhost:3306/itmsdb
      username: root
      password: 123456
#      schema: database/itmsdb.sql
#      sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      hibernate:
        ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect